apiVersion: platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: nate-cluster-x-azure
spec:
  id: nate-cluster-x-azure #be unique
  cloud: azure #gcp or azure
  region: "eastus2" #regions: [gcp - "us-west1" "us-west2" "us-east1" "us-east2"] [azure - "eastus" "eastus2" "westus2" "westus3"]
  parameters:
    nodes:
      count: 3 #1-100
      size: small #small/medium/large
