apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure.xnetworks.azure.platformref.upbound.io
  labels:
    cloud: azure
spec:
  compositeTypeRef:
    apiVersion: platformref.upbound.io/v1alpha1
    kind: XNetwork
  resources:
    - base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        spec:
          forProvider:
            location: eastus2
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.annotations[upbound.io/external-name]
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.labels[azure.platformref.upbound.io/app]
    - base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: VirtualNetwork
        spec:
          forProvider:
            resourceGroupNameSelector:
              matchControllerRef: true
            location: eastus2
            addressSpace: ['192.168.0.0/16']
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.labels[app]
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-vnet"
      - fromFieldPath: spec.id
        toFieldPath: metadata.annotations[upbound.io/external-name]
        transforms:
          - type: string
            string:
              fmt: "%s-vnet"
    - base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            resourceGroupNameSelector:
              matchControllerRef: true
            virtualNetworkNameSelector:
              matchControllerRef: true
            addressPrefixes: 
              - "192.168.1.0/24"
            serviceEndpoints: ["Microsoft.Sql"]
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.labels[azure.platformref.upbound.io/app]
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-sn"
      - fromFieldPath: spec.id
        toFieldPath: metadata.annotations[upbound.io/external-name]
        transforms:
          - type: string
            string:
              fmt: "%s-sn"
