apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure.xk8s.platformref.upbound.io
  labels:
    cloud: azure
spec:
  compositeTypeRef:
    apiVersion: platformref.upbound.io/v1alpha1
    kind: XK8s
  resources:
    - base:
        apiVersion: containerservice.azure.upbound.io/v1beta1
        kind: KubernetesCluster       
        spec:
          forProvider:
            privateClusterPublicFqdnEnabled: true
            location: "eastus2" #patched
            kubernetesVersion: "1.22.6" #version: "1.21.9" | "1.22.6"
            defaultNodePool:
              - name: default
                nodeCount: 1 #patched
                vmSize: Standard_B2s #patched
                enableAutoScaling: false
            identity:
              - type: "SystemAssigned"
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
        - fromFieldPath: spec.id
          toFieldPath: metadata.annotations[upbound.io/external-name]
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.upbound.io/app]
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.location
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.defaultNodePool[0].vnetSubnetIDSelector.matchLabels[azure.platformref.upbound.io/app]
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.dnsPrefix
        - fromFieldPath: spec.parameters.node.size
          toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
          transforms:
            - type: map
              map:
                small: Standard_B2s
                medium: Standard_B4ms
                large: Standard_DS3_v2
        - fromFieldPath: "spec.parameters.nodes.count"
          toFieldPath: "spec.forProvider.defaultNodePool[0].nodeCount"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.writeConnectionSecretToRef.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-akscluster"

