apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane
  namespace: upbound-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crossplane
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crossplane
    spec:
      containers:
      - args:
        - core
        - start
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: olala
          value: olala
        - name: LEADER_ELECTION
          value: "true"
        image: upbound/crossplane:v1.8.1-up.2
        imagePullPolicy: IfNotPresent
        name: universal-crossplane
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsUser: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: package-cache
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - core
        - init
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: upbound/crossplane:v1.8.1-up.2
        imagePullPolicy: IfNotPresent
        name: universal-crossplane-init
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsUser: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: crossplane
      serviceAccountName: crossplane
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 1024Mi
        name: package-cache

